# Created by following these resources:
# - https://docs.travis-ci.com/user/languages/java/
# - https://docs.travis-ci.com/user/sonarcloud/
# - https://github.com/SonarSource/sq-com_example_java-gradle-travis
language: java
jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: "jonjam-github"
    token:
      secure: $SONAR_TOKEN

services:
  - docker

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

stages:
  - build
  - name: deploy
    if: branch = master AND type IN (push)

jobs:
  include:
    - stage: build
      before_script:
      - if [[ ! $PWD/ = "/home/travis/build/JonJam/pinboard-map" ]]; then cd "/home/travis/build/JonJam/pinboard-map"; fi
      script:
      - ./gradlew build --no-daemon
      - ./gradlew sonarqube --no-daemon
    - stage: deploy
      skip_cleanup: true
      provider: script
      install: skip
      before_script:
      - if [[ ! $PWD/ = "/home/travis/build/JonJam/pinboard-map" ]]; then cd "/home/travis/build/JonJam/pinboard-map"; fi
      script:
      - bash scripts/docker_push.sh