import com.bmuschko.gradle.tomcat.extension.TomcatPluginExtension
import com.bmuschko.gradle.tomcat.tasks.Tomcat

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds/
 */

plugins {
    id("org.sonarqube") version "2.7"
    // TODO Remove tomcat plugin
    id("com.bmuschko.tomcat") version "2.5" apply false
}

// Enabling dependency locking. See https://docs.gradle.org/current/userguide/dependency_locking.html.
allprojects {
    repositories {
        jcenter()
    }

    // Locking for configurations. See https://docs.gradle.org/current/userguide/dependency_locking.html.
    dependencyLocking {
        lockAllConfigurations()
    }

    buildscript {
        dependencyLocking {
            lockAllConfigurations()
        }
    }

    // Declare version. See https://docs.gradle.org/current/userguide/building_java_projects.html#introduction
    version = "0.0.1"
}

subprojects {
    // TODO Refactor below as and when to only be common stuff.
    apply(plugin = "java")
    apply(plugin = "war")
    apply(plugin = "checkstyle")
    apply(plugin = "com.bmuschko.tomcat")

    // Use dependency constraints. See https://docs.gradle.org/current/userguide/declaring_dependencies.html#declaring_a_dependency_without_version
    dependencies {
        constraints {
            "implementation"("org.glassfish.jersey.containers:jersey-container-servlet:2.27+")
            // javax.xml.bind:jaxb-api and javax.activation:activation are needed to prevent errors. See https://www.jeffryhouser.com/index.cfm/2017/12/21/Why-wont-Jersey-work-on-JDK-9
            "implementation"("javax.xml.bind:jaxb-api:2.3+")
            "implementation"("javax.activation:activation:1.1+")

            // TODO Remove this and swap to Guice
            "implementation"("org.glassfish.jersey.inject:jersey-hk2:2.27+")

            // TODO Re-enable Jackson
            // "implementation"("org.glassfish.jersey.media:jersey-media-json-jackson:2.+")
            // TODO Re-enable Guice
            // "implementation"("org.glassfish.hk2:guice-bridge:2.+")
            "testImplementation"("org.junit.jupiter:junit-jupiter-api:5.+")
            "testImplementation"("org.junit.jupiter:junit-jupiter-params:5.+")
            "testRuntimeOnly"("org.junit.jupiter:junit-jupiter-engine:5.+")

            "tomcat"("org.apache.tomcat.embed:tomcat-embed-core:9.0.1")
            "tomcat"("org.apache.tomcat.embed:tomcat-embed-jasper:9.0.1")
        }
    }

    // Set compatibility. See https://docs.gradle.org/current/userguide/building_java_projects.html#introduction
    configure<JavaPluginConvention> {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    // Performance suggestions for Java projects. See https://guides.gradle.org/performance/#suggestions_for_java_projects
    tasks.withType<JavaCompile> {
        options.isFork = true
    }

    tasks.withType<Test> {
        maxParallelForks = (Runtime.getRuntime().availableProcessors() / 2).takeIf { it > 0 } ?: 1

        setForkEvery(100)

        reports.html.isEnabled = false
        reports.junitXml.isEnabled = false
    }

    configure<TomcatPluginExtension> {
        httpProtocol = "org.apache.coyote.http11.Http11Nio2Protocol"
        ajpProtocol = "org.apache.coyote.ajp.AjpNio2Protocol"
    }
}