version: '3'
services:
  location:
    build:
      context: ..
      args:
        VERSION: dev

    container_name: location-$USER
    hostname: location-$USER

    image: jonjam/pinboard-map-location:master

    ports:
      - "8031:8031" # HTTP
      - "8431:8431" # HTTPS
      - "7031:7031" # JMX
      - "4031:4031" # DEBUG

    volumes:
      - ../location-svc/build/exploded:/usr/local/tomcat/webapps/ROOT

    environment:
      # Used to determine which environment configuration to load.
      - ENVIRONMENT=dev

      - SUSPEND_STARTUP=n

      # log4j2: Use dev logging i.e. console.
      - LOG4J_CONFIGURATION_FILE=log4j2-dev.xml