version: '3'
services:
  location:
    build:
      context: ../.

    container_name: location

    image: jonjam/pinboard-map-location:master

    ports:
      - "8031:8031" # HTTP
      - "8431:8431" # HTTPS
      - "7031:7031" # JMX
      - "4031:4031" # DEBUG

    volumes:
      - ../location-svc/build/exploded:/usr/local/tomcat/webapps/ROOT

    environment:
      - SUSPEND_STARTUP=${SUSPEND_STARTUP:-n}